### ISSUE TITLE
Configuration Tuning Advisor Dashboard

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#122]
A new configuration tuning advisor page. Based on recent usage, shows advice for setting / adjusting:
table_definition_cache
table_open_cache
innodb_adaptive_hash_index
innodb_io_capacity
innodb_io_capacity_max
innodb_log_buffer_size
innodb_log_file_size
innodb_read_io_threads
innodb_write_io_threads

**Comment by oblitorum** [comment]
Do we have the rules of advice for these configs? e.g. for `innodb_read_io_threads`/`innodb_write_io_threads`, if the pending reads/writes is above **50** and the Disk I/O Utilization is less than **50%**, we should double the `innodb_read_io_threads`/`innodb_write_io_threads`, as memtioned in this [issue](https://github.com/shatteredsilicon/ssm-submodules/issues/105) .

Also, does showing these advice settings as table sounds right? e.g.

| setting | current value | advice value |
| ------- | --------------- | ------------- |
| innodb_read_io_threads | 4 | 8 |
| innodb_write_io_threads | 4 | 8 |
| ... | ... | ... |

**Comment by oblitorum** [comment]
It reminds me the **mtuned** project which we have left off for a while 😂 , seems familiar.

**Comment by gordan-bobic** [comment]
Yes, it is very similar to mtuned, only mtuned didn't have access to history data that is in ssm, and with data history in ssm we can make a much more educated guess by looking at days or weeks of data.

What we should have on this page is:
On the left, graph based on which we make the decision for a particular setting.

On the right, current value and proposed value (could be the same value if no change needed). Highlighted in green if recommended value == current value, otherwise in yellow.

**Comment by oblitorum** [comment]
Does this looks right?

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/ac8d9212-5a44-49ee-9d30-d983758eaab0)

One setting per row, if the current value doesn't match proposed value, the background will turn into yellow, proposed stat will always have green background.

**Comment by gordan-bobic** [comment]
That looks good. Make the recommended value the same background colour as everything else.
Maybe also shrink the font a notch or two, so that 4 characters fit, e.g. 256K

**Comment by oblitorum** [comment]
OK, got it. And we don't need to worry about the font size, it will be adjusted automatically to fit the dashboard

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/000e7b67-70b3-4096-b839-d96d4ef3a3d0)

**Comment by gordan-bobic** [comment]
My concern is that it will look weird if different rows have different size numbers.

**Comment by oblitorum** [comment]
OK, let me see if there is way to keep both of the size in sync

**Comment by gordan-bobic** [comment]
Additional:
- binlog_cache_size and binlog_stmt_cache_size tuning. If the hit rate is below 95%, advise doubling it.
Relates to: https://github.com/shatteredsilicon/ssm-submodules/issues/161

- Estimate maximum theoretical memory usage based on the following equation:
```
SELECT (
           (
               @@binlog_file_cache_size +
               @@innodb_buffer_pool_size +
               @@innodb_log_buffer_size +
               @@key_buffer_size +
               @@query_cache_size +
               ( @@max_connections *
                   ( @@binlog_cache_size +
                     @@binlog_stmt_cache_size +
                     @@bulk_insert_buffer_size +
                     @@join_buffer_size +
                     @@max_allowed_packet +
                     @@read_buffer_size +
                     @@read_rnd_buffer_size +
                     @@sort_buffer_size +
                     @@thread_stack +
                     @@tmp_table_size
                   )
               ) +
               ( @@slave_parallel_threads * 
                 ( @@slave_parallel_max_queued )
               ) +
               ( @@open_files_limit * 1024)
           ) / 1024 / 1024 / 1024) AS max_memory_GB;
```
Show amount in MB/GB/TB, as appropriate, and as a % of total system RAM.
If this exceeds 80% of RAM show it in yellow. If it exceeds 90% of RAM, show it in red.

Is there a way we could present this visually in Grafana? Using some kind of a rectangular block graph, e.g. on the X axis we have max_connections an then horizontal lines of different thickness, with thickness proportional to the size allocated for each per-connection metric.

Then another rectangle with slave_parallel_threads on X axis and slave_parallel_max_queued on the Y axis, but sized so that surface area is proportional to the per-connection rectangle.

A third rectangle with globally allocated memory (innodb_buffer_pool_size, key_buffer_size, etc).

These three should be proportional to each other, e.g. 10x10 pixel block per MB or per GB or something like that, depending on how much memory is allocated.

And finally a 4th rectangle or pie chart that shows how much memory could be allocated on each of the above 3 sections, relative to each other.

Is something even remotely close to this achieavable with Grafana?

**Comment by oblitorum** [comment]
You mean these dashboards should look something like this?

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/952bd966-4d97-4593-a584-fa778bb5f302)

And Regard of those 3 rectangular block graph, show max_connections/slave_parallel_threads/(what for globally allocated memory ?) as X axis instead of time points, e.g. The max_connection is 64, then we should show 64 columns of those memory block.

Also for connection memory and globally memory dashboards, we should have horizontal lines of different metrics, e.g.

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/67fedd58-22c2-464e-a3ac-02399e134c63)

Something like these can't be done with Grafana original panel as far as I can tell, but we can always create our own panel type as 3rd party plugin, with which we can customize the dashboard with HTML/CSS/JS quite freely.

**Comment by gordan-bobic** [comment]
Yes, that looks really good. The only way it could be better is if the three memory "pixel map" type charts were proportional in size.

**Comment by oblitorum** [comment]
You mean, for example, the connection memory is 2x larger than slave memory, then the connection memory dashboard should have 2x more memory blocks than the slave memory dashboard, which makes the connection memory dashboard itself is 2x larger than the slave memory dashboard?

**Comment by oblitorum** [comment]
On a separate note, the current Tuning Advisor Dashboards look like this

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/74cb9019-6dfa-4987-9413-046da6a19e09)

And the logic for advising is:

- table_definition_cache: if total table amount (rows in `information_schema.tables`) >= `table_definition_cache`, advise doubling it.
- table_open_cache: if `Open_tables` (from output of `SHOW GLOBAL STATUS`) >= `75% table_open_cache`, advise doubling it.
- innodb_log_buffer_size: if InnoDB recovery log lsn size since last flush ('Log sequence number' - 'Log flushed up to', from output of `SHOW ENGINE INNODB STATUS`) in past 7 days was spotted at >= `75% innodb_log_buffer_size`, advise increasing it to the next power of 2.
- innodb_log_file_size: if max checkpoint age ('Log sequence number' - 'Last checkpoint at', from output of `SHOW ENGINE INNODB STATUS`) in past 7 days was spotted at >= `75% total redo log size` (total redo log size = innodb_log_files_in_group * innodb_log_file_size), advise increasing it to the next power of 2.
- innodb_io_capacity_max: with last-7-days's average disk IO utilization and disk io/s data, infer what the maximum disk io/s would be, and if innodb_io_capacity_max is lower than 75% of that maximum value, advise increasing it to 75% of that maximum value.
- innodb_io_capacity: if it's not equal 50% of innodb_io_capacity_max, advise setting it to 50% innodb_io_capacity_max.
- innodb_read_io_threads: if the average pending I/O reads in past 7 days > 0 and disk I/O utilization < 75%, propose the value to the next power of 2.
- innodb_write_io_threads: if the average pending I/O writes in past 7 days > 0 and disk I/O utilization < 75%, propose the value to the next power of 2.
- binlog_cache_size: if average hit ratio in past 7 days is below 95%, advise doubling it.
- binlog_stmt_cache_size: if average hit ratio in past 7 days is below 95%, advise doubling it.

Please correct me if there is anything needs to be fixed.

**Comment by gordan-bobic** [comment]
Looks good overall!
Adjustments - most recommendations should be rounded up to the next power of 2 (if nothing else for more legible my.cnf values):
- table_definition_cache: count(information_schema.tables) rounded up to next 2^n (1024 in this example)
- table_open_cache: round up to the next 2^n (1024 in this example)

- innodb_io_capacity_max: 31.5 iops /1.46% makes estimated disk capability of ~2151 iops. So 75% would be about 1613. We should thus advise this rounded down to nearest power of 2 (1024). But - we should never reduce this below the default (2,000) https://mariadb.com/kb/en/innodb-system-variables/#innodb_io_capacity_max

- innodb_read_io_threads / innodb_write_io_threads: if the average pending I/O [reads | writes] in past 7 days > 0
s/average/max/ - we tune this to minimize peak impact
Corresponding Disk I/O should be measured for whether it exceeds 75% during the same period during which peak pending writes were observed.

- binlog_cache_size / binlog_stmt_cache_size: 0 here seems to be misleading. Can we check this against whether:
1) binlog is enabled
2) any binlog is actually getting generated
Otherwise we end up advising doubling this to infinity when binlog is idle or disabled.

**Comment by gordan-bobic** [comment]
> You mean, for example, the connection memory is 2x larger than slave memory, then the connection memory dashboard should have 2x more memory blocks than the slave memory dashboard, which makes the connection memory dashboard itself is 2x larger than the slave memory dashboard?

s/dashboard/graph/, but yes. It's to provide visual representation of where to look first for reducing the potentially insane maximum theoretical memory consumption.

**Comment by oblitorum** [comment]
OK, the current Advisor Dashboard page looks like this

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/3a8a293e-876c-4608-b395-b84ab48dad38)

Those 3 memory block graphs are implemented like this

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/766a8ded-0d0a-46ea-9ffa-cd9a48b61171)

One memory block represents 16MB, because I found that there would be too many blocks if per MB and too few blocks if per GB.
Metrics those horizontal lines represent are listed on the left, and it will show the size when it hovers.

Also, the new `tmp_table_size` setting is added for advising. The logic is, advise setting it to previous power of 2 of maximum value of `@@tmp_table_size / Tmp_Memory_Fit_Rate` in past 7 days, but never above 1% of total memory.

And last, I just notice that I missed the `innodb_adaptive_hash_index` setting advising, what would be the proper logic for this? e.g. advise disabling it if AHI hit ratio is less than 50%, but when to advise enabling it?

**Comment by gordan-bobic** [comment]
That looks quite awesome. :-)

For AHI I think we need to look at:
AHI Hits / ((AHI Hits) + (AHI maintenance (rows added + removed + updated)))
Below 50%, we advise switching it off as it means it maintenance cost outweighs the benefit.

On a related note, remember there's a bug fix you discovered (also in Percona's PMM2) in calculation of the AHI hit rate, I think you already fixed it in the master branch.

**Comment by oblitorum** [comment]
OK, but when to advise switching AHI ON if it's OFF? Or we never advise switching it ON because it requires many manual analytics by human in reality?

**Comment by gordan-bobic** [comment]
AHI is on by default.
>= 50% hit rate => ON
< 50% => OFF

**Comment by oblitorum** [comment]
But ain't there no AHI hits if it's OFF? How do we know what the hit rate is and advise switching it ON?

**Comment by gordan-bobic** [comment]
Yes - if it is off - we have no way of knowing whether it should be or not. But since it is ON by default, we just have to assume that the human that actively disabled it knew what they were doing. So just make the recommendation "N/A"

**Comment by oblitorum** [comment]
OK, got it
