### ISSUE TITLE
When monitoring RDS nodes, having one node without Enhanced Monitoring prevents ALL RDS telemetry from being gathered for ALL monitored nodes

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#204]
Setup:
- Multiple RDS nodes, with enhanced monitoring enabled
- Add a RDS node with enhanced monitoring disabled

Result:
- RDS telemetry (CPU, memory) stops being collected for all monitored RDS nodes

Additional:
- The node cannot be fully deleted using the "Monitored Instances" page. Pressing the delete button and refreshing the page always makes it re-appear, and telemetry on all node continues to not work.

If I purge and re-set everything, I can re-add the other nodes to make things work again, but that isn't a workable solution because we lose all accumulated telemetry.

Enabling enhanced monitoring on that one node, makes everything start working again, so there is a check somewhere that is global for enhanced monitoring when it should be per monitored server.

**Comment by oblitorum** [comment]
The problem "one enhanced-monitoring-disabled node prevents all nodes' temlemetry" was fixed with this PR -> https://github.com/shatteredsilicon/rds_exporter/pull/9

And I added another patch https://github.com/shatteredsilicon/ssm-managed/pull/34 to make sure the further node deletion operations on the "Monitored instances" page works if previous operation somehow failed.
