### ISSUE TITLE
Insight / Advisor Dashboard

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#256]
- Rename from "Advisor Dashboard" to "Advisor - Tuning"
- innodb_log_buffer_size and innodb_redo_log_capacity/innodb_log_file_size graphs are the same, and they shouldn't be,
- Is there any way to make the block graphs (e.g. memory usage) have a hover-over like other graphs to that you can just hover over it with a mouse and it tells you what that colour code is?
- it looks like the colours of the squares don't match the colour coding legend

**Comment by oblitorum** [comment]
> It looks like the colours of the squares don't match the colour coding legend

In order to make the green blocks visible through the thickness, I made the color half transparent. and because the colors on the left are on top of a dark gray background, and the colors on the right are on top of a green background (those memory blocks), which somehow makes it look different.

![image](https://github.com/user-attachments/assets/de0fb918-509c-43fd-aa56-aff17af7acf3)


If we make it non-transparent, they will look just the same, but it will look like this, which is not quite acceptable.

![image](https://github.com/user-attachments/assets/d6705bc7-a100-40f5-a60c-ecf85b926c5d)

Also there is a problem with the current way it shows those thickness - Say `max_allowed_packet` and `tmp_table_size` are both **2 GB**, their represent rectangles will have the exact same size, e.g. there are actually 2 rectangles in the highlight area in then below image, one for `max_allowed_packet` and another for `tmp_table_size`, but one of them is 'hidden'. We may need to think of a way to solve this, e.g. divide the rectangle, or privode a second action so one can select which rectangle to see.

![image](https://github.com/user-attachments/assets/eaae1383-012e-409c-ba58-164fb3c594cc)
 
Considering the above issues, maybe we can use a different way to represent those allocated memory, like showing different allocated memory directly on the memory blocks:

![image](https://github.com/user-attachments/assets/3a582be3-6a8b-473f-9169-b85b8841a800)

We can still have the popup when we hover over the memory blocks, also currently one memory block represents **16 MB**, say `binlog_stmt_cache_size` is **5 MB**, less than one memory block, and then we can make the relevant memory block smaller, like the one in the above image.

What do you think? One of the downside could be that it seems a little 'colorful', not sure if using a darker color schema will make it better.

**Comment by gordan-bobic** [comment]
Can we make it stretch to the full surface area of the graph? That would improve resolution, possibly to a point where the problem becomes irrelevant. Importance of allocation is proportional to theme size. So if one of the tiny allocation disappears below the noise floor, it doesn't really matter.

**Comment by oblitorum** [comment]
You mean like this? Yeah, we can do that I think.
Which mean the size that a memory block represents will be different depending on what total allocated memory size is, it could be **8 MB** if total allocated memory is **8 GB**, or **4 MB** if allocated memory is **4 GB**

![image](https://github.com/user-attachments/assets/a32b4582-2520-449b-9dc4-1736a98dc4a4)

**Comment by gordan-bobic** [comment]
I think that looks better. Or we make the squares smaller, e.g. 4x4 or 8x8 pixels.

**Comment by oblitorum** [comment]
OK, it looks like this now

![image](https://github.com/user-attachments/assets/7f350e19-1610-41a4-9ca2-05477c63163b)

If this looks ok, then this [PR](https://github.com/shatteredsilicon/grafana-dashboards/pull/61) is ready to be merged.
