### ISSUE TITLE
Try to adjust Grafana 9 font size on graphs

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#259]
The font size of numbers on landing page mini-graphs is all over the place. Investigate if something can be done to make it a bit more consistent like it was on Grafana 5.

**Comment by oblitorum** [comment]
Tried to set a fixed font size for those mini graphs that may appear with a larger font size, here is the result:

before

![image](https://github.com/user-attachments/assets/41940bf3-c15f-4b7e-ba42-3a00746d8f3d)

after

![image](https://github.com/user-attachments/assets/68007e66-1b48-4510-a967-19a528ac7f81)

Will that do?

Also changed the thresholds/colors settings of the Network IO mini graph, so that it's similar to those Disk/DB mini graphs, is that OK?

**Comment by gordan-bobic** [comment]
That looks like a significant improvement.
