### ISSUE TITLE
Investigate if it is possible to switch to a minimal Rocky EL8 image to reduce the size pt. 1

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#28]
The SSM container image is significantly bigger than the PMM v1 image. Please investigate if it is possible to use a smaller / minimal EL8 image to shrink the SSM image size as far as possible.

**Comment by oblitorum** [comment]
Managed to shrink it to about **`1.6 GB`** (slightly different between architectures), it's mostly because `ansible` from RHEL 8 bigger than the one in PMM v1, so I use `pip` tool to install the smaller version. 

Other than that the size difference is coming from dependencies/libraries and new dependencies added to SSM (clamav/rkhunter).

**Comment by gordan-bobic** [comment]
Please stick with EL8 supplied packages wherever possible.
Otherwise we have even more of a security tracing problem than we already do with all the golang and npm dependencies.
If it won't go any smaller, that's fine, I'd rather have a slightly bigger image than more dependency variables to track for security issues.

**Comment by oblitorum** [comment]
OK, got it
