### ISSUE TITLE
Spurious user @buildkitsandbox in the QAN database

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#282]
```
MariaDB [mysql]> select user, host from user;
+-------------+-----------------+
| User        | Host            |
+-------------+-----------------+
|             | buildkitsandbox |
```
Identify where this comes from and why, and remove from the database initialisation because it almost certainly isn't used. (can't be relevant when we are operating through a UNIX socket).

**Comment by oblitorum** [comment]
OK, turns out that during the ssm-server image build time, docker sets the hostname of its running internal container as 'buildkitsandbox', and then those ansible mysql tasks use an anonymous user to connect to mariadb, hence leaving a `''@'buildkitsandbox'` user in the mysql.user table.

I think we could just delete that `''@'buildkitsandbox'` at the end of the ssm-server image build.

**Comment by gordan-bobic** [comment]
Yes, sounds good. Drop the user at the end of the build process.
