### ISSUE TITLE
Feature: Toggle Button for Auto-Creating Server Alerts

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#320]
On the SSM / Monitored Instances dashboard:
- Have a toggle button, similar to the one on the adding RDS nodes screen
- When toggled to on, it creates a default alerting dashboard for the server, based on the default alerting dashboard template
- When toggled to off, it deletes the alerting dashboard and all the alerts associated with it.

When toggling to off, show a confirmation dialog:
"Deleting the alerting dashboard will also delete any changes that may have been manually made to it. Aure you sure?" Yes/No

**Comment by oblitorum** [comment]
I'm thinking putting the template files in repo [grafana-dashboards](https://github.com/shatteredsilicon/grafana-dashboards), since all grafana dashboard files go there.

And we may need a templating language for this, I'm thinking using the Go template language. Since the [ssm-managed](https://github.com/shatteredsilicon/ssm-managed) is responsible for receiving the request from web interface and generating the alert dashboard, and it's written in Go. And yes, it's also not a problem if we choose another templating language or just simply use `###SERVER_NAME###` as the placeholder.

**Comment by gordan-bobic** [comment]
That all sounds good. We need to be able to change the dashboard if we need to by copying s new json file in. This shouldn't change existing alerts, but should change alerts created going forward. Also see conversation elsewhere about separating alerts and not having a separate dashboard for each server, only separate alerts.

As for templating language, ###SERVER_NAME### was just a quick and dirty hack to get things done in a few minutes. If there is a better way, let's use it.

**Comment by oblitorum** [comment]
OK, added the alert button to the Monitored Instances page, it looks like this

![image](https://github.com/user-attachments/assets/7a315916-84cc-4c85-a276-7bef2b4367b1)

Once the alert button of a monitored server is switched on, it will generate specific alert rules for this server, and these alert rules are named in pattern `${alert_rule_title} - ${monitored_server_name}`, as shown in this image

![image](https://github.com/user-attachments/assets/3fb5285e-b106-48b2-b4af-40b49fa698fc)

And all these auto-generated alert rules will be associated with specific panel in the new Health Check dashboard

![image](https://github.com/user-attachments/assets/35113ade-6efa-4ec4-9923-bd06968ddb5e)

**Comment by gordan-bobic** [comment]
This looks pretty awesome.
