### ISSUE TITLE
Latest dev image (9.4.3-6) breaks when upgrading with SELinux enabled

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#340]
To reproduce, do the following on a SELinux enabled/enforcing machine:

```
podman create \
   -v /opt/prometheus/data \
   -v /opt/consul-data \
   -v /var/lib/mysql \
   -v /var/lib/grafana \
   --name ssm-data \
   shatteredsilicon/ssm-server:9.4 /bin/true

podman run -d \
   -p 80:80 -p 443:443 \
   --volumes-from ssm-data \
   --name ssm \
   --restart always \
   -e SERVER_USER=ssm \
   -e SERVER_PASSWORD=ssm \
   -e DEBUG=1 \
   docker.io/shatteredsilicon/ssm-server:9.4
```

Connect with browser to `http://localhost` to make sure it works.

```
podman stop ssm
podman rm ssm
docker load -i https://dl.shatteredsilicon.net/ssm-dev/9/ssm-server-x86_64-9.4.3-6.tgz

podman run -d \
   -p 80:80 -p 443:443 \
   --volumes-from ssm-data \
   --name ssm \
   --restart always \
   -e SERVER_USER=ssm \
   -e SERVER_PASSWORD=ssm \
   -e DEBUG=1 \
   docker.io/shatteredsilicon/ssm-server-x86_64:9.4.3-6
```

The container startup will fail and grafana web interface will never come up.

**Comment by gordan-bobic** [comment]
This looks like it was actually caused by a podman bug. Can no longer reproduce on latest version.

**Comment by oblitorum** [comment]
I also encounted into this and found out this problem does exist, and the key is it only goes wrong after you upgrade it 2 times. e.g.

```
$ podman create ... --name ssm-data
$ podman run ... --name ssm
$ stop and rm the ssm container, upgrade it with a newer version of SSM the first time (this is OK)
$ stop and rm the ssm container, upgrade it with a newer version of SSM the second time (it goes wrong from now on)
```

And the problem seems to be caused by [this](https://github.com/python/cpython/issues/83074) - python's cp library doesn't necessarily determine that it is running inside a container and copies the MCS labels across filesystems (from ssm runtime container to ssm-data container).

Ideally files on a mounted volume should have lable like this (without the tailing cXXX,cXXX MCS label):
```
bash-5.1# ls -Z /var/lib/grafana/plugins/ | grep ssm-app
unconfined_u:object_r:container_file_t:s0 ssm-app
```

But when the `import-dashboards.py` python script kicks in and copies the new dashboard files from runtime container to data container, the lable becomes like this:
```
bash-5.1# ls -Z /var/lib/grafana/plugins/ | grep ssm-app
system_u:object_r:container_file_t:s0:c769,c852 ssm-app
```
Hence there will be a problem when the next different runtime container tries to access these files.

Luckily it doesn't seem to have this problem with docker-ce, because docker-ce doesn't follow the MCS policy or something.

**Comment by oblitorum** [comment]
I created a PR [here](https://github.com/shatteredsilicon/ssm-server/pull/54) to use a `cp` system call rather than python's cp library function to fix this.
