### ISSUE TITLE
Newly upgraded node_exporter.conf results has cpu = false

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#346]
I suspect this is related to the fix for:
https://github.com/shatteredsilicon/ssm-submodules/issues/307

After upgrading from ssm-client 9.4.1 release to current dev, cpu telemetry is disabled by default.

It seems to affect other settings as well:
```
cpu = false
meminfo = false
diskstats = false
filesystem = false
netclass = false
netdev = false
netstat = false
```

The bottom to graphs on OS -> Network Overview dashboard - echos and mask requests - show "No data". What exporter options need to be enabled for these to populate?

Even with all of the above enabled (should be enabled by default), the landing page doesn't show disk stats, reads and writes both show "N/A".
Host uptime also shows up as "N/A"

**Comment by oblitorum** [comment]
Yeah, this is related to the fix for https://github.com/shatteredsilicon/ssm-submodules/issues/307 , it doesn't handle the upgrade well in some cases I think.

I reckon there is an empty `[collectors].enabled` setting in the config file? e.g.
```
[collectors]
enabled =
```
Try remove that settings completely, and those telemetry should appear.

Will fix this.
