### ISSUE TITLE
Landing page shows disk reads/writes = N/A

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#347]
It looks like with latest ssm-client / ssm-server image, on the landing page disk reads/writes both show up as N/A.

Host uptime also shows up as N/A

Clicking on the disk read to go do OS / Disk Performance leads to host=all rather than to host=$host selected on the landing page. This also happens for clicking on CPU usage or DB connections - $host is not preserved. I recall we had a similar problem before. I'm guessing the patch that was applied for Grafana 9.x either wasn't applied or needs to be modified for Grafana 11.x.

**Comment by oblitorum** [comment]
> It looks like with latest ssm-client / ssm-server image, on the landing page disk reads/writes both show up as N/A.
> 
> Host uptime also shows up as N/A

Did you wait enough time (say 5+ mins ) for them to show up?  Somehow the metrics on new Grafana (say 9.2.10+) are shown up slower than earlier Grafana (say 5.4.5), but they eventually show up.

<img width="1680" alt="Screenshot 2024-12-04 at 08 59 56" src="https://github.com/user-attachments/assets/004e2a81-9a7c-4f39-8436-90f65c4b87d0">

However, it seems the data doesn't update as frequently as before. e.g. I ran `sysbench` for testing, and the actual cpu usage wasn't shown up at the landing page immediately, it still showed a low cpu usage, I had to wait longer time for it to change, and it feels like it's showing the average metrics instead of a real-time metrics. I think I will need to adjust some settings/queries to fix it.

> Clicking on the disk read to go do OS / Disk Performance leads to host=all rather than to host=$host selected on the landing page. This also happens for clicking on CPU usage or DB connections - $host is not preserved. I recall we had a similar problem before. I'm guessing the patch that was applied for Grafana 9.x either wasn't applied or needs to be modified for Grafana 11.x.

Yeah, this problem indeed exists. Will fix this.

**Comment by gordan-bobic** [comment]
Looks fixed now, closing.
